# .pre-commit-config.yaml
repos:
  # repository with hook definitions
  - repo: https://github.com/CharlesLe114/personal-hooks
    rev: main # release version of the repo
    hooks: # list of hooks from the repo to include in this project
      - id: print-argument
